apiVersion: apps/v1
kind: Deployment
metadata:
  name: maliev-commerce-service
spec:
  template:
    spec:
      containers:
        - name: maliev-commerce-service
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Staging"
