apiVersion: v1
kind: ServiceAccount
metadata:
  name: legacy-quotation-migration
  namespace: maliev-legacy
  labels:
    app.kubernetes.io/name: legacy-quotation-migration
    app.kubernetes.io/part-of: maliev-legacy
automountServiceAccountToken: false
