apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: maliev-prod
  namespace: argocd
spec:
  description: "Production environment applications"
  sourceRepos:
    - "https://github.com/MALIEV-Co-Ltd/maliev-gitops.git"
  destinations:
    - namespace: maliev-prod
      server: https://kubernetes.default.svc
  permitOnlyProjectScopedClusters: true
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
