apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: maliev-notification-service-secrets
spec:
  target:
    name: maliev-notification-service-secrets
  dataFrom:
    - extract:
        key: maliev-dev-notification-service-config
