apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: maliev-material-service-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: maliev-material-service-secrets
    creationPolicy: Owner
  data:
    - secretKey: Jwt__PublicKey
      remoteRef:
        key: maliev-prod-shared-config
        property: Jwt__PublicKey
    - secretKey: Jwt__Issuer
      remoteRef:
        key: maliev-prod-shared-config
        property: Jwt__Issuer
    - secretKey: Jwt__Audience
      remoteRef:
        key: maliev-prod-shared-config
        property: Jwt__Audience
    - secretKey: ServiceAuthentication__ClientSecret
      remoteRef:
        key: maliev-prod-material-service-config
        property: ServiceAuthentication__ClientSecret
    - secretKey: ConnectionStrings__MaterialDbContext
      remoteRef:
        key: maliev-prod-material-service-config
        property: ConnectionStrings__MaterialDbContext
    - secretKey: ConnectionStrings__rabbitmq
      remoteRef:
        key: maliev-prod-shared-config
        property: ConnectionStrings__rabbitmq
    - secretKey: ConnectionStrings__redis
      remoteRef:
        key: maliev-prod-shared-config
        property: ConnectionStrings__redis
    - secretKey: CORS__AllowedOrigins
      remoteRef:
        key: maliev-prod-shared-config
        property: CORS__AllowedOrigins
