apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: maliev-quote-engine-secrets
spec:
  dataFrom:
    - extract:
        key: maliev-service-config
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: maliev-quote-engine-secrets
