apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/MALIEV-Co-Ltd/Legacy.Maliev.EmployeeService.git//deploy/base?ref=f901f601f661d54d394d263191a9180d0c37182a
