apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: maliev-currency-service-secrets
spec:
  target:
    name: maliev-currency-service-secrets
  data:
    - secretKey: Jwt__PublicKey
      remoteRef:
        key: maliev-dev-shared-config
        property: Jwt__PublicKey
    - secretKey: Jwt__Issuer
      remoteRef:
        key: maliev-dev-shared-config
        property: Jwt__Issuer
    - secretKey: Jwt__Audience
      remoteRef:
        key: maliev-dev-shared-config
        property: Jwt__Audience
    - secretKey: ServiceAuthentication__ClientSecret
      remoteRef:
        key: maliev-dev-currency-service-config
        property: ServiceAuthentication__ClientSecret
    - secretKey: ConnectionStrings__CurrencyDbContext
      remoteRef:
        key: maliev-dev-currency-service-config
        property: ConnectionStrings__CurrencyDbContext
    - secretKey: ConnectionStrings__rabbitmq
      remoteRef:
        key: maliev-dev-shared-config
        property: ConnectionStrings__rabbitmq
    - secretKey: ConnectionStrings__redis
      remoteRef:
        key: maliev-dev-shared-config
        property: ConnectionStrings__redis
    - secretKey: CORS__AllowedOrigins
      remoteRef:
        key: maliev-dev-shared-config
        property: CORS__AllowedOrigins
