kind: Kustomization

namespace: maliev-dev

resources:
- ../../base

images:
- name: asia-southeast1-docker.pkg.dev/maliev-website/maliev-website-artifact/maliev-leave-service
  newName: asia-southeast1-docker.pkg.dev/maliev-website/maliev-website-artifact-dev/maliev-leave-service
  newTag: b724b7ae1a9e44d9dfe481744da8a216e12e5204
apiVersion: kustomize.config.k8s.io/v1beta1
