kind: Kustomization

namespace: maliev-dev

resources:
- ../../base

images:
- name: asia-southeast1-docker.pkg.dev/maliev-website/maliev-website-artifact/maliev-leave-service
  newName: asia-southeast1-docker.pkg.dev/maliev-website/maliev-website-artifact-dev/maliev-leave-service
  newTag: 7c6bcd359b55b9c5dae3b4f5c9019edf934c5557
apiVersion: kustomize.config.k8s.io/v1beta1
