kind: Kustomization

namespace: maliev-dev

resources:
- ../../base

images:
- name: asia-southeast1-docker.pkg.dev/maliev-website/maliev-website-artifact/maliev-leave-service
  newName: asia-southeast1-docker.pkg.dev/maliev-website/maliev-website-artifact-dev/maliev-leave-service
  newTag: 06a4b83d672dcaf5a5d91c8666e292e8248b357b
apiVersion: kustomize.config.k8s.io/v1beta1
