kind: Kustomization

namespace: maliev-dev

resources:
- ../../base

images:
- name: asia-southeast1-docker.pkg.dev/maliev-website/maliev-website-artifact/maliev-compliance-service
  newName: asia-southeast1-docker.pkg.dev/maliev-website/maliev-website-artifact-dev/maliev-compliance-service
  newTag: 43020dae4a2e79a0267803a503573c1afb48fcf3
apiVersion: kustomize.config.k8s.io/v1beta1
