apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: asia-southeast1-docker.pkg.dev/maliev-website/maliev-website-artifact/maliev-intranet
  newName: asia-southeast1-docker.pkg.dev/maliev-website/maliev-website-artifact-dev/maliev-intranet
  newTag: 8cf312398a75f92d3d34be97b710ca12f6692b68

namespace: maliev-dev

resources:
- ../../base

patches:
- path: environment-config-patch.yaml
- path: resource-limits-patch.yaml
- path: health-check-patch.yaml
- path: logging-config-patch.yaml
- path: service-secrets-patch.yaml
- path: hpa-patch.yaml
