apiVersion: apps/v1
kind: Deployment
metadata:
  name: maliev-country-service
spec:
  template:
    spec:
      containers:
        - name: maliev-country-service
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Staging"
            - name: Services__AuthService__BaseUrl
              value: "https://staging.api.maliev.com"
            - name: Services__IAMService__BaseUrl
              value: "https://staging.api.maliev.com"
