apiVersion: v1
kind: ServiceAccount
metadata:
  name: legacy-maliev-web
  namespace: maliev-legacy
  annotations:
    iam.gke.io/gcp-service-account: legacy-maliev-web@maliev-website.iam.gserviceaccount.com
automountServiceAccountToken: false
