apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: asia-southeast1-docker.pkg.dev/maliev-website/maliev-website-artifact/maliev-project-service
  newName: asia-southeast1-docker.pkg.dev/maliev-website/maliev-website-artifact-dev/maliev-project-service
  newTag: 2602bd4095a83177c6ada465db95f2b4bba41137

namespace: maliev-dev

resources:
- ../../base

patches:
- path: environment-config-patch.yaml
