apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: asia-southeast1-docker.pkg.dev/maliev-website/maliev-website-artifact/maliev-delivery-service
  newName: asia-southeast1-docker.pkg.dev/maliev-website/maliev-website-artifact-dev/maliev-delivery-service
  newTag: 6a6a31919178815c7c73ed7da48380a4cac7a78d

namespace: maliev-dev

resources:
- ../../base

patches:
- path: environment-config-patch.yaml
- path: resource-limits-patch.yaml
- path: health-check-patch.yaml
- path: service-secrets-patch.yaml
- path: hpa-patch.yaml
