kind: Kustomization

namespace: maliev-dev

resources:
- ../../base

images:
- name: asia-southeast1-docker.pkg.dev/maliev-website/maliev-website-artifact/maliev-lifecycle-service
  newName: asia-southeast1-docker.pkg.dev/maliev-website/maliev-website-artifact-dev/maliev-lifecycle-service
  newTag: fb608431b1bdce7090369172592b30e918073c0a
apiVersion: kustomize.config.k8s.io/v1beta1
