kind: Kustomization

namespace: maliev-dev

resources:
- ../../base

images:
- name: asia-southeast1-docker.pkg.dev/maliev-website/maliev-website-artifact/maliev-lifecycle-service
  newName: asia-southeast1-docker.pkg.dev/maliev-website/maliev-website-artifact-dev/maliev-lifecycle-service
  newTag: 7e744445759c9861a04c9fd60f38ef1b4aa79eef
apiVersion: kustomize.config.k8s.io/v1beta1
