kind: Kustomization

namespace: maliev-dev

resources:
- ../../base

images:
- name: asia-southeast1-docker.pkg.dev/maliev-website/maliev-website-artifact/maliev-compensation-service
  newName: asia-southeast1-docker.pkg.dev/maliev-website/maliev-website-artifact-dev/maliev-compensation-service
  newTag: 14d2b5552a8bc0a96a16af2e22c4011aec08c32b
apiVersion: kustomize.config.k8s.io/v1beta1
