kind: Kustomization

namespace: maliev-dev

resources:
- ../../base

images:
- name: asia-southeast1-docker.pkg.dev/maliev-website/maliev-website-artifact/maliev-compensation-service
  newName: asia-southeast1-docker.pkg.dev/maliev-website/maliev-website-artifact-dev/maliev-compensation-service
  newTag: 42d5c7d30a3ef20abe75d5cef3ce26210f77fd2c
apiVersion: kustomize.config.k8s.io/v1beta1
