apiVersion: apps/v1
kind: Deployment
metadata:
  name: maliev-search-service
spec:
  template:
    spec:
      containers:
        - name: maliev-search-service
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              cpu: 250m
              memory: 512Mi
