apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: maliev-quote-engine-secrets
spec:
  target:
    name: maliev-quote-engine-secrets
  dataFrom:
    - extract:
        key: maliev-staging-quote-engine-config
