apiVersion: v1
kind: Service
metadata:
  name: maliev-currency-service
  labels:
    app: maliev-currency-service
spec:
  type: ClusterIP
  selector:
    app: maliev-currency-service
  ports:
    - name: http
      port: 80
      targetPort: 8080
