apiVersion: apps/v1
kind: Deployment
metadata:
  name: maliev-material-service
spec:
  template:
    spec:
      containers:
        - name: maliev-material-service
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: Services__AuthService__BaseUrl
              value: "https://api.maliev.com"
            - name: Services__IAMService__BaseUrl
              value: "https://api.maliev.com"
            - name: Services__SupplierService__BaseUrl
              value: "https://api.maliev.com"
