apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: legacy-redis
  labels:
    app.kubernetes.io/name: legacy-redis
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: legacy-redis
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        REDIS_PASSWORD: "{{ .redisPassword }}"
  data:
    - secretKey: redisPassword
      remoteRef:
        key: maliev-legacy-secrets
        property: legacy-redis-password
