apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: asia-southeast1-docker.pkg.dev/maliev-website/maliev-website-artifact/maliev-inventory-service
  newName: asia-southeast1-docker.pkg.dev/maliev-website/maliev-website-artifact-dev/maliev-inventory-service
  newTag: 359ac451cb0fb56be6cd43cb7617e40306d4c56f

namespace: maliev-dev

resources:
- ../../base

patches:
- path: environment-config-patch.yaml
