apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: asia-southeast1-docker.pkg.dev/maliev-website/maliev-website-artifact/maliev-inventory-service
  newName: asia-southeast1-docker.pkg.dev/maliev-website/maliev-website-artifact-dev/maliev-inventory-service
  newTag: 094d7f5d2ca6c013fce8fa039f86a601fc2d28f9

namespace: maliev-dev

resources:
- ../../base

patches:
- path: environment-config-patch.yaml
