apiVersion: v1
kind: Service
metadata:
  name: maliev-commerce-service
  labels:
    app: maliev-commerce-service
spec:
  type: NodePort
  selector:
    app: maliev-commerce-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
