apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: asia-southeast1-docker.pkg.dev/maliev-website/maliev-website-artifact/maliev-facility-service
  newName: asia-southeast1-docker.pkg.dev/maliev-website/maliev-website-artifact-dev/maliev-facility-service
  newTag: 73f02498cce644e92d9591612a3d74a4378162a0

namespace: maliev-dev

resources:
- ../../base

patches:
- path: environment-config-patch.yaml
- path: resource-limits-patch.yaml
- path: health-check-patch.yaml
- path: logging-config-patch.yaml
- path: service-secrets-patch.yaml
- path: hpa-patch.yaml
