apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: legacy-maliev-country-service
  labels:
    app.kubernetes.io/name: legacy-maliev-country-service
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: legacy-maliev-country-service
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        ConnectionStrings__CountryDbContext: >-
          Host=legacy-postgres-main-rw;Port=5432;Database=Country;Username={{ .countryUsername }};Password={{ .countryPassword }};SSL Mode=Require;Trust Server Certificate=true;Pooling=true;Minimum Pool Size=0;Maximum Pool Size=20
        ConnectionStrings__redis: "legacy-redis:6379,password={{ .redisPassword }},ssl=false,abortConnect=false"
        Jwt__PublicKey: "{{ .jwtPublicKey }}"
        Jwt__Issuer: "{{ .jwtIssuer }}"
        Jwt__Audience: "{{ .jwtAudience }}"
  data:
    - secretKey: countryUsername
      remoteRef:
        key: maliev-legacy-secrets
        property: legacy-postgres-country-username
    - secretKey: countryPassword
      remoteRef:
        key: maliev-legacy-secrets
        property: legacy-postgres-country-password
    - secretKey: jwtPublicKey
      remoteRef:
        key: maliev-legacy-secrets
        property: legacy-jwt-public-key
    - secretKey: jwtIssuer
      remoteRef:
        key: maliev-legacy-secrets
        property: legacy-jwt-issuer
    - secretKey: jwtAudience
      remoteRef:
        key: maliev-legacy-secrets
        property: legacy-jwt-audience
    - secretKey: redisPassword
      remoteRef:
        key: maliev-legacy-secrets
        property: legacy-redis-password
