apiVersion: apps/v1
kind: Deployment
metadata:
  name: maliev-quote-engine
spec:
  template:
    spec:
      containers:
        - name: maliev-quote-engine
          resources:
            requests:
              cpu: 20m
              memory: 256Mi
            limits:
              cpu: 60m
              memory: 384Mi
