apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: maliev-legacy
resources:
  - ../../base
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/environment: legacy
images:
  - name: legacy-maliev-notification-service
    newName: asia-southeast1-docker.pkg.dev/maliev-website/maliev-website-artifact-prod/legacy-maliev-notification-service
    newTag: not-published
