apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: legacy-postgres-superuser
  labels:
    app.kubernetes.io/name: legacy-postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: legacy-postgres-superuser
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: maliev-legacy-secrets
        property: legacy-postgres-superuser-username
    - secretKey: password
      remoteRef:
        key: maliev-legacy-secrets
        property: legacy-postgres-superuser-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: legacy-postgres-country
  labels:
    app.kubernetes.io/name: legacy-postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: legacy-postgres-country
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: maliev-legacy-secrets
        property: legacy-postgres-country-username
    - secretKey: password
      remoteRef:
        key: maliev-legacy-secrets
        property: legacy-postgres-country-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: legacy-postgres-currency
  labels:
    app.kubernetes.io/name: legacy-postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: legacy-postgres-currency
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: maliev-legacy-secrets
        property: legacy-postgres-currency-username
    - secretKey: password
      remoteRef:
        key: maliev-legacy-secrets
        property: legacy-postgres-currency-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: legacy-postgres-customer
  labels:
    app.kubernetes.io/name: legacy-postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: legacy-postgres-customer
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: maliev-legacy-secrets
        property: legacy-postgres-customer-username
    - secretKey: password
      remoteRef:
        key: maliev-legacy-secrets
        property: legacy-postgres-customer-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: legacy-postgres-customer-identity
  labels:
    app.kubernetes.io/name: legacy-postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: legacy-postgres-customer-identity
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: maliev-legacy-secrets
        property: legacy-postgres-customer-identity-username
    - secretKey: password
      remoteRef:
        key: maliev-legacy-secrets
        property: legacy-postgres-customer-identity-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: legacy-postgres-data-protection-keys
  labels:
    app.kubernetes.io/name: legacy-postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: legacy-postgres-data-protection-keys
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: maliev-legacy-secrets
        property: legacy-postgres-data-protection-keys-username
    - secretKey: password
      remoteRef:
        key: maliev-legacy-secrets
        property: legacy-postgres-data-protection-keys-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: legacy-postgres-data-protection-keys-employee
  labels:
    app.kubernetes.io/name: legacy-postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: legacy-postgres-data-protection-keys-employee
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: maliev-legacy-secrets
        property: legacy-postgres-data-protection-keys-employee-username
    - secretKey: password
      remoteRef:
        key: maliev-legacy-secrets
        property: legacy-postgres-data-protection-keys-employee-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: legacy-postgres-employee
  labels:
    app.kubernetes.io/name: legacy-postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: legacy-postgres-employee
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: maliev-legacy-secrets
        property: legacy-postgres-employee-username
    - secretKey: password
      remoteRef:
        key: maliev-legacy-secrets
        property: legacy-postgres-employee-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: legacy-postgres-employee-identity
  labels:
    app.kubernetes.io/name: legacy-postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: legacy-postgres-employee-identity
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: maliev-legacy-secrets
        property: legacy-postgres-employee-identity-username
    - secretKey: password
      remoteRef:
        key: maliev-legacy-secrets
        property: legacy-postgres-employee-identity-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: legacy-postgres-invoice
  labels:
    app.kubernetes.io/name: legacy-postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: legacy-postgres-invoice
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: maliev-legacy-secrets
        property: legacy-postgres-invoice-username
    - secretKey: password
      remoteRef:
        key: maliev-legacy-secrets
        property: legacy-postgres-invoice-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: legacy-postgres-job-offers
  labels:
    app.kubernetes.io/name: legacy-postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: legacy-postgres-job-offers
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: maliev-legacy-secrets
        property: legacy-postgres-job-offers-username
    - secretKey: password
      remoteRef:
        key: maliev-legacy-secrets
        property: legacy-postgres-job-offers-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: legacy-postgres-material
  labels:
    app.kubernetes.io/name: legacy-postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: legacy-postgres-material
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: maliev-legacy-secrets
        property: legacy-postgres-material-username
    - secretKey: password
      remoteRef:
        key: maliev-legacy-secrets
        property: legacy-postgres-material-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: legacy-postgres-message
  labels:
    app.kubernetes.io/name: legacy-postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: legacy-postgres-message
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: maliev-legacy-secrets
        property: legacy-postgres-message-username
    - secretKey: password
      remoteRef:
        key: maliev-legacy-secrets
        property: legacy-postgres-message-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: legacy-postgres-order
  labels:
    app.kubernetes.io/name: legacy-postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: legacy-postgres-order
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: maliev-legacy-secrets
        property: legacy-postgres-order-username
    - secretKey: password
      remoteRef:
        key: maliev-legacy-secrets
        property: legacy-postgres-order-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: legacy-postgres-order-status
  labels:
    app.kubernetes.io/name: legacy-postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: legacy-postgres-order-status
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: maliev-legacy-secrets
        property: legacy-postgres-order-status-username
    - secretKey: password
      remoteRef:
        key: maliev-legacy-secrets
        property: legacy-postgres-order-status-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: legacy-postgres-payment
  labels:
    app.kubernetes.io/name: legacy-postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: legacy-postgres-payment
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: maliev-legacy-secrets
        property: legacy-postgres-payment-username
    - secretKey: password
      remoteRef:
        key: maliev-legacy-secrets
        property: legacy-postgres-payment-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: legacy-postgres-purchase-order
  labels:
    app.kubernetes.io/name: legacy-postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: legacy-postgres-purchase-order
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: maliev-legacy-secrets
        property: legacy-postgres-purchase-order-username
    - secretKey: password
      remoteRef:
        key: maliev-legacy-secrets
        property: legacy-postgres-purchase-order-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: legacy-postgres-quotation
  labels:
    app.kubernetes.io/name: legacy-postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: legacy-postgres-quotation
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: maliev-legacy-secrets
        property: legacy-postgres-quotation-username
    - secretKey: password
      remoteRef:
        key: maliev-legacy-secrets
        property: legacy-postgres-quotation-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: legacy-postgres-quotation-request
  labels:
    app.kubernetes.io/name: legacy-postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: legacy-postgres-quotation-request
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: maliev-legacy-secrets
        property: legacy-postgres-quotation-request-username
    - secretKey: password
      remoteRef:
        key: maliev-legacy-secrets
        property: legacy-postgres-quotation-request-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: legacy-postgres-receipt
  labels:
    app.kubernetes.io/name: legacy-postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: legacy-postgres-receipt
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: maliev-legacy-secrets
        property: legacy-postgres-receipt-username
    - secretKey: password
      remoteRef:
        key: maliev-legacy-secrets
        property: legacy-postgres-receipt-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: legacy-postgres-supplier
  labels:
    app.kubernetes.io/name: legacy-postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: legacy-postgres-supplier
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: maliev-legacy-secrets
        property: legacy-postgres-supplier-username
    - secretKey: password
      remoteRef:
        key: maliev-legacy-secrets
        property: legacy-postgres-supplier-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: legacy-postgres-upload
  labels:
    app.kubernetes.io/name: legacy-postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: legacy-postgres-upload
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: maliev-legacy-secrets
        property: legacy-postgres-upload-username
    - secretKey: password
      remoteRef:
        key: maliev-legacy-secrets
        property: legacy-postgres-upload-password
