apiVersion: apps/v1
kind: Deployment
metadata:
  name: maliev-registry-service
spec:
  template:
    spec:
      containers:
        - name: maliev-registry-service
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: Services__AuthService__BaseUrl
              value: "https://dev.api.maliev.com"
            - name: Services__IAMService__BaseUrl
              value: "https://dev.api.maliev.com"
