apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: maliev-geometry-service-secrets
spec:
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: maliev-geometry-service-secrets
  data:
    - secretKey: RABBITMQ_URI
      remoteRef:
        key: rabbitmq-connection-string
    - secretKey: JWT_PUBLIC_KEY
      remoteRef:
        key: jwt-public-key
    - secretKey: JWT_PRIVATE_KEY
      remoteRef:
        key: jwt-private-key
    - secretKey: JWT_SECURITY_KEY
      remoteRef:
        key: jwt-security-key
    - secretKey: JWT_ISSUER
      remoteRef:
        key: jwt-issuer
    - secretKey: JWT_AUDIENCE
      remoteRef:
        key: jwt-audience
