kind: Kustomization

namespace: maliev-dev

resources:
- ../../base

images:
- name: asia-southeast1-docker.pkg.dev/maliev-website/maliev-website-artifact-dev/maliev-performance-service
  newName: asia-southeast1-docker.pkg.dev/maliev-website/maliev-website-artifact-dev/maliev-performance-service
  newTag: 2cffd1e9f47834ba8884edb08eb2da513fb9985c
- name: asia-southeast1-docker.pkg.dev/maliev-website/maliev-website-artifact/maliev-performance-service
  newName: asia-southeast1-docker.pkg.dev/maliev-website/maliev-website-artifact-dev/maliev-performance-service
  newTag: 2b055606200facee0437a75be5697dc9e1babd07
apiVersion: kustomize.config.k8s.io/v1beta1
