apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: maliev-legacy
resources:
- ../../base
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/environment: legacy
images:
- name: legacy-maliev-country-service
  newName: asia-southeast1-docker.pkg.dev/maliev-website/maliev-website-artifact-prod/legacy-maliev-country-service
  newTag: dcc1958bc21e1aa223ee7b4a1c01704e53cb829a
