apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: maliev-dev

resources:
- ../../base

images:
- name: asia-southeast1-docker.pkg.dev/maliev-website/maliev-website-artifact/maliev-pricing-service
  newName: asia-southeast1-docker.pkg.dev/maliev-website/maliev-website-artifact-dev/maliev-pricing-service
  newTag: 29cfbd778473e39987e424e82b53b50a40e101b7
