apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: maliev-dev

resources:
- ../../base

images:
- name: asia-southeast1-docker.pkg.dev/maliev-website/maliev-website-artifact/maliev-pricing-service
  newName: asia-southeast1-docker.pkg.dev/maliev-website/maliev-website-artifact-dev/maliev-pricing-service
  newTag: 041adb1f8b062f3e9197b16a472b08d645ee3dd8
