apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: asia-southeast1-docker.pkg.dev/maliev-website/maliev-website-artifact/maliev-prediction-service
  newName: asia-southeast1-docker.pkg.dev/maliev-website/maliev-website-artifact-dev/maliev-prediction-service
  newTag: 2577351d3e87ac5e8c3795ef90d4f8e79e45864d

namespace: maliev-dev

resources:
- ../../base

patches:
- path: environment-config-patch.yaml
- path: resource-limits-patch.yaml
- path: health-check-patch.yaml
- path: service-secrets-patch.yaml
