apiVersion: apps/v1
kind: Deployment
metadata:
  name: maliev-search-service
spec:
  template:
    spec:
      containers:
        - name: maliev-search-service
          livenessProbe:
            httpGet:
              path: /search/liveness
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /search/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
