apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: maliev-search-service-secrets
spec:
  target:
    name: maliev-search-service-secrets
  dataFrom:
    - extract:
        key: maliev-dev-search-service-config
