apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: asia-southeast1-docker.pkg.dev/maliev-website/maliev-website-artifact/maliev-job-service
  newName: asia-southeast1-docker.pkg.dev/maliev-website/maliev-website-artifact-dev/maliev-job-service
  newTag: e0ba944cf972906cd100bbb2c9812c3bb9963412

namespace: maliev-dev

resources:
- ../../base

patches:
- path: environment-config-patch.yaml
