apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: legacy-postgres-migration-control
  namespace: maliev-legacy
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: legacy-postgres-migration-control
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: maliev-legacy-secrets
        property: legacy-postgres-migration-control-username
    - secretKey: password
      remoteRef:
        key: maliev-legacy-secrets
        property: legacy-postgres-migration-control-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: legacy-postgres-migration-shadow
  namespace: maliev-legacy
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: legacy-postgres-migration-shadow
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: maliev-legacy-secrets
        property: legacy-postgres-migration-shadow-username
    - secretKey: password
      remoteRef:
        key: maliev-legacy-secrets
        property: legacy-postgres-migration-shadow-password
